/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["activity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admission"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agreements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["agreements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agreements/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["agreement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["assets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/official": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["official_assets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["offers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["release"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["wallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Activity: {
            agreement: string;
            /** Format: int64 */
            createdAt: number;
            createdTerms?: null | components["schemas"]["Terms"];
            id: string;
            lastValidBlockHeight: string;
            operation: components["schemas"]["Operation"];
            owner: string;
            signature: string;
            status: components["schemas"]["Status"];
            /** Format: int64 */
            updatedAt: number;
        };
        ActivityPage: {
            items: components["schemas"]["Activity"][];
            next?: string | null;
            /** @description Independent of pagination, so older unresolved operations remain recoverable. */
            pending: components["schemas"]["Activity"][];
        };
        Admission: {
            mint: string;
            newCommitments: boolean;
            reason: string;
        };
        AgreementView: {
            acceptBefore: string;
            address: string;
            designatedHolder?: string | null;
            expiresAt: string;
            finalizedSlot: string;
            holder?: string | null;
            netReceived: string;
            /** Format: int64 */
            observedAt: number;
            payout: string;
            /** Format: int32 */
            policyVersion: number;
            premium: string;
            quantityRaw: string;
            reserve: string;
            reserveAmount: string;
            settlement: string;
            status: string;
            /** Format: int32 */
            underlyingDecimals: number;
            underlyingMint: string;
            underlyingProgram: string;
            usdcMint: string;
            /** Format: int32 */
            version: number;
            writer: string;
        };
        AssetView: {
            /** Format: int32 */
            decimals: number;
            mint: string;
            name: string;
            referenceMint: string;
            source: string;
            symbol: string;
        };
        Deployment: {
            assets: components["schemas"]["AssetView"][];
            authority: string;
            genesisHash: string;
            localnet?: null | components["schemas"]["LocalFixtures"];
            mode: string;
            programId: string;
            programLength: number;
            programSha256: string;
            /** Format: int32 */
            schemaVersion: number;
            upgradeAuthority?: string | null;
            usdcMint: string;
        };
        /** @enum {string} */
        Eligibility: "compatible" | "unsupported" | "unreviewed" | "expired" | "stale" | "unavailable";
        ErrorBody: {
            code: string;
            message: string;
        };
        FeeSchedule: {
            /** Format: int32 */
            basisPoints: number;
            epoch: string;
            maximumRaw: string;
        };
        LocalFixtures: {
            /** Format: int32 */
            fixtureVersion: number;
            holder: string;
            holderUsdc: string;
            writer: string;
            writerUsdc: string;
        };
        MarketContext: {
            impliedValuation?: string | null;
            markPrice?: string | null;
            markValuation?: string | null;
            /**
             * Format: int64
             * @description The public response supplies no price timestamp or verified price/display-unit contract.
             */
            observedAt?: number | null;
            supply?: string | null;
            tokenPrice?: string | null;
            unitsVerified: boolean;
        };
        MintEvidence: {
            authorities: {
                [key: string]: string | null;
            };
            currentFee?: null | components["schemas"]["FeeSchedule"];
            /** Format: int32 */
            decimals: number;
            displayMultiplier?: string | null;
            extensions: string[];
            /** Format: int64 */
            multiplierEffectiveAt?: number | null;
            nextDisplayMultiplier?: string | null;
            nextFee?: null | components["schemas"]["FeeSchedule"];
            restrictions: string[];
            supplyRaw: string;
            tokenProgram: string;
            transparentTransferSupported: boolean;
        };
        OfficialAsset: {
            chain?: null | components["schemas"]["MintEvidence"];
            eligibility: components["schemas"]["Eligibility"];
            market?: null | components["schemas"]["MarketContext"];
            mint: string;
            name: string;
            policy?: null | components["schemas"]["ReviewedAsset"];
            reason: string;
            symbol: string;
        };
        OfficialCatalog: {
            assets: components["schemas"]["OfficialAsset"][];
            chainSource: components["schemas"]["SourceObservation"];
            finalizedSlot?: string | null;
            genesisHash: string;
            marketSource: components["schemas"]["SourceObservation"];
            network: string;
            source: string;
        };
        /** @enum {string} */
        Operation: "create" | "activate" | "exercise" | "cancel" | "reclaim" | "cleanup";
        Release: {
            localnet: boolean;
            programSha256?: string | null;
            revision?: string | null;
            version: string;
        };
        ReviewedAsset: {
            /** Format: int64 */
            conversionDeadline?: number | null;
            /** Format: int32 */
            decimals: number;
            /** Format: int64 */
            expiryBufferSeconds: number;
            /** Format: int64 */
            maxExpiry: number;
            mint: string;
            name: string;
            /** Format: int64 */
            reviewedAt: number;
            /** Format: int64 */
            reviewedUntil: number;
            source: string;
            symbol: string;
        };
        SourceObservation: {
            error?: string | null;
            /** Format: int64 */
            receivedAt?: number | null;
            status: components["schemas"]["SourceStatus"];
        };
        /** @enum {string} */
        SourceStatus: "fresh" | "stale" | "unavailable";
        /** @enum {string} */
        Status: "pending" | "provisional" | "finalized" | "failed" | "expired" | "reconciled" | "unresolved";
        Terms: {
            acceptBefore: string;
            designatedHolder?: string | null;
            expiresAt: string;
            nonce: string;
            payout: string;
            premium: string;
            quantityRaw: string;
            underlyingMint: string;
        };
        WalletTokenAccount: {
            address: string;
            amountRaw: string;
            /** Format: int32 */
            decimals: number;
            finalizedSlot: string;
            frozen: boolean;
            mint: string;
            tokenProgram: string;
        };
        WalletView: {
            accounts: components["schemas"]["WalletTokenAccount"][];
            owner: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    activity: {
        parameters: {
            query: {
                owner: string;
                before?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityPage"];
                };
            };
        };
    };
    admission: {
        parameters: {
            query: {
                mint: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Admission"];
                };
            };
        };
    };
    agreements: {
        parameters: {
            query?: {
                /** @description Last address from the previous page (exclusive). */
                after?: string;
                /** @description Page size, from 1 to 200. Defaults to 50. */
                limit?: number;
                holder?: string;
                writer?: string;
                mint?: string;
                status?: string;
                /** @description Exact underlying quantity in base units; offers are never resized. */
                quantity_raw?: string;
                min_payout?: string;
                max_premium?: string;
                /** @description Include unrestricted offers and offers reserved for this holder, excluding their own offers. */
                eligible_holder?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Exclusive address cursor for the next page; absent on the last page */
                    "X-Next-Cursor"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgreementView"][];
                };
            };
        };
    };
    agreement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgreementView"];
                };
            };
        };
    };
    assets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetView"][];
                };
            };
        };
    };
    official_assets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfficialCatalog"];
                };
            };
        };
    };
    config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deployment"];
                };
            };
        };
    };
    offers: {
        parameters: {
            query?: {
                /** @description Last address from the previous page (exclusive). */
                after?: string;
                /** @description Page size, from 1 to 200. Defaults to 50. */
                limit?: number;
                holder?: string;
                writer?: string;
                mint?: string;
                status?: string;
                /** @description Exact underlying quantity in base units; offers are never resized. */
                quantity_raw?: string;
                min_payout?: string;
                max_premium?: string;
                /** @description Include unrestricted offers and offers reserved for this holder, excluding their own offers. */
                eligible_holder?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Exclusive address cursor for the next page; absent on the last page */
                    "X-Next-Cursor"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgreementView"][];
                };
            };
        };
    };
    release: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Release"];
                };
            };
        };
    };
    wallet: {
        parameters: {
            query: {
                owner: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletView"];
                };
            };
        };
    };
}
