/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/agreements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["agreements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agreements/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["agreement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["assets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["offers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["positions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AgreementView: {
            acceptBefore: string;
            address: string;
            designatedHolder?: string | null;
            expiresAt: string;
            finalizedSlot: string;
            holder?: string | null;
            netReceived: string;
            /** Format: int64 */
            observedAt: number;
            payout: string;
            /** Format: int32 */
            policyVersion: number;
            premium: string;
            quantityRaw: string;
            reserve: string;
            reserveAmount: string;
            settlement: string;
            status: string;
            underlyingMint: string;
            underlyingProgram: string;
            usdcMint: string;
            /** Format: int32 */
            version: number;
            writer: string;
        };
        AssetView: {
            /** Format: int32 */
            decimals: number;
            mint: string;
            name: string;
            provenance: string;
            symbol: string;
        };
        Deployment: {
            authority: string;
            /** Format: int32 */
            fixtureVersion: number;
            genesisHash: string;
            holder: string;
            holderUnderlying: string;
            holderUsdc: string;
            mode: string;
            programId: string;
            programLength: number;
            programSha256: string;
            /** Format: int32 */
            schemaVersion: number;
            underlyingMint: string;
            usdcMint: string;
            writer: string;
            writerUsdc: string;
        };
        ErrorBody: {
            code: string;
            message: string;
        };
        PositionView: {
            amountRaw: string;
            /** Format: int32 */
            decimals: number;
            finalizedSlot: string;
            mint: string;
            owner: string;
            tokenAccount: string;
            usdcAmountRaw: string;
            usdcTokenAccount: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    agreements: {
        parameters: {
            query?: {
                /** @description Last address from the previous page (exclusive). */
                after?: string;
                /** @description Page size, from 1 to 200. Defaults to 50. */
                limit?: number;
                holder?: string;
                writer?: string;
                mint?: string;
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Exclusive address cursor for the next page; absent on the last page */
                    "X-Next-Cursor"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgreementView"][];
                };
            };
        };
    };
    agreement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgreementView"];
                };
            };
        };
    };
    assets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetView"][];
                };
            };
        };
    };
    config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deployment"];
                };
            };
        };
    };
    offers: {
        parameters: {
            query?: {
                /** @description Last address from the previous page (exclusive). */
                after?: string;
                /** @description Page size, from 1 to 200. Defaults to 50. */
                limit?: number;
                holder?: string;
                writer?: string;
                mint?: string;
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Exclusive address cursor for the next page; absent on the last page */
                    "X-Next-Cursor"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgreementView"][];
                };
            };
        };
    };
    positions: {
        parameters: {
            query: {
                owner: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionView"][];
                };
            };
        };
    };
}
